title: 'Python Numerical Methods'
author: ''
logo: notebooks/images/book_cover.jpg
copyright: '2020'

execute:
  execute_notebooks: off

repository:
  url: https://pythonnumericalmethods.berkeley.edu

# launch_buttons:
#     binderhub_url: https://mybinder.org
#     jupyterhub_url: https://datahub.berkeley.edu

html:
#   favicon: content/images/favicon.ico
  use_repository_button: true
  navbar_number_sections: false
